source('c:/code/ARM/bin/ARMSTr.r')
setwd('C:/Users/peter/AppData/Local/Temp/ARM/3044/')
require(grDevices)
means.vector <- read.delim('trialMeans.SmyCol2.tab',header=FALSE)
means.matrix <- read.delim('trialTable.SmyCol2.tab',header=FALSE)
means.vector <- means.vector[,1]
bmp('TxTSmyCol2.bmp', width = 620, height = 500, units = 'px', pointsize = 14, bg = 'white')
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 5, 2, 1) + 0.1), ps = 14, cex.lab = 1, cex.main = 1.142857, cex.axis = 1)
plot.interaction.ARMST(means.matrix, means.vector, ylab='Treatment in Trial Mean \nTW',regression=TRUE, main='Treatment Stability and Trial Clusters for Grand Mean 2', show.legend=TRUE,legend.columns=2, legend.pos=c(.01,.98))
par(fig=c(0,1,0,.4),mar=(c(4, 5, 0, 1) + 0.1), new=TRUE)
plot.clusters.ARMST(means.matrix, means.vector, xlab='Trial Mean \nCPT_2007Subset', ylab='')
dev.off()
par(fig = c(0, 1, 0, 1))
