---
title: "Exploring Treatment x Trial
  Interactions using Treatment Stability/Trial Dendrogram plots"
author: "Peter Claussen"
date: "October 15, 2015"
output: html_document
---


Here I use the CPT 2007 data set to illustrate new options avialable for ST Treatment Stability/Trial Dendrogram plots.

```{r,echo=FALSE}
library(ARMR)
source("../ASA_CSSA_SSSA/R/gei.table.to.frame.R")
source("../ASA_CSSA_SSSA/R/nonadditivity.gei.R")
source("../ASA_CSSA_SSSA/R/heterogeneity.gei.R")
source("../ASA_CSSA_SSSA/R/standard.sensitivity.plot.R")
source("../ASA_CSSA_SSSA/R/expand.incidence.R")
source("../ASA_CSSA_SSSA/R/decompose.means.table.R")
source("../ASA_CSSA_SSSA/R/interaction.outliers.R")
source("../ASA_CSSA_SSSA/R/plot.interaction.ARMST.R")
```

### Multilocation

Using scripts from ARM ST to show options.
```{r}
path = "../Manuscripts/scripts/multilocation"
means.vector <- read.delim('../Manuscripts/scripts/multilocation/trialMeans.SmyCol1.tab',header=FALSE)
means.matrix <- read.delim('../Manuscripts/scripts/multilocation/trialTable.SmyCol1.tab',header=FALSE)
means.vector <- means.vector[,1]
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 6, 2, 1) + 0.1), ps = 12, cex.lab = 1.166667, cex.main = 1.333333, cex.axis = 1)
res1<-plot.interaction.ARMST(means.matrix, means.vector, ylab='Treatment in Trial Mean \nYield',regression=TRUE, main='Treatment Stability and Trial Clusters for Grand Mean 1', show.legend=TRUE,legend.columns=1, legend.pos=c(.01,.98))
par(fig=c(0,1,0,.4),mar=(c(4, 6, 0, 1) + 0.1), new=TRUE)
res2<-plot.clusters.ARMST(means.matrix, means.vector, xlab='Trial Mean \nMultilocation', ylab='')
par(fig = c(0, 1, 0, 1))
```

```{r}
path = "../Manuscripts/scripts/multilocation"
means.vector <- read.delim('../Manuscripts/scripts/multilocation/trialMeans.SmyCol1.tab',header=FALSE)
means.matrix <- read.delim('../Manuscripts/scripts/multilocation/trialTable.SmyCol1.tab',header=FALSE)
means.vector <- means.vector[,1]
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 6, 2, 1) + 0.1), ps = 12, cex.lab = 1.166667, cex.main = 1.333333, cex.axis = 1)
res1<-plot.interaction.ARMST(means.matrix, means.vector, ylab='Treatment in Trial Mean \nYield',regression=TRUE, main='Treatment Stability and Trial Clusters for Grand Mean 1', show.legend=TRUE,legend.columns=1, legend.pos=c(.01,.98))
par(fig=c(0,1,0,.4),mar=(c(4, 6, 0, 1) + 0.1), new=TRUE)
decomp <- decompose.means.table(means.matrix)
fg="black"
res2<-plot.clusters.ARMST(means.matrix, means.vector, fg=fg,xlab='Trial Mean \nMultilocation', ylab='',reference=(decomp$mu + decomp$alpha + decomp$beta))
fg="yellow"

res3 <- plot.clusters.ARMST(decomp$mu + decomp$alpha + decomp$beta, means.vector, fg=fg,add=TRUE,xlab='Trial Mean \nMultilocation', ylab='')
par(fig = c(0, 1, 0, 1))
```

```{r}
str(res2$means.hc)

res2$means.hc$height
res3$means.hc$height

res2$means.hc$height/res3$means.hc$height
res2$means.hc$order
res3$means.hc$order

res2$means.hc$merge
res3$means.hc$merge

res2$means.hc$merge==res3$means.hc$merge

matched.idx <- compare.merges(res2$means.hc$merge,res3$means.hc$merge)
matched.idx
res2$means.hc$height
res3$means.hc$height
res3$means.hc$height[matched.idx]
```

```{r}
The function cluster.stats() in the fpc package provides a mechanism for comparing the similarity of two cluster solutions using a variety of validation criteria (Hubert's gamma coefficient, the Dunn index and the corrected rand index)
# comparing 2 cluster solutions
library(fpc)
cluster.stats(d, fit1$cluster, fit2$cluster)
where d is a distance matrix among objects, and fit1$cluster and fit$cluster are integer vectors containing classification results from two different clusterings of the same data.
```

```{r}
library(SASmixed)
data(Multilocation)
mixed.res <- standard.sensitivity.plot(Multilocation,
                                     response = "Adj",
                          TreatmentName = "Trt",
                          TrialName = "Location",
                          RepName="Block",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=1)
print.stdplot(mixed.res)

```

```{r,echo=FALSE}
ny84.dat <- data.frame(
Entry=as.factor(c("EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL","EVAN","WILK","CHIP","HODG","S200","CORS","WELL")),
Environment=as.factor(c("A77","A77","A77","A77","A77","A77","A77","C77","C77","C77","C77","C77","C77","C77","V77","V77","V77","V77","V77","V77","V77","V78","V78","V78","V78","V78","V78","V78","A79","A79","A79","A79","A79","A79","A79","C79","C79","C79","C79","C79","C79","C79","G79","G79","G79","G79","G79","G79","G79","R79","R79","R79","R79","R79","R79","R79","V79","V79","V79","V79","V79","V79","V79","A80","A80","A80","A80","A80","A80","A80","C80","C80","C80","C80","C80","C80","C80","G80","G80","G80","G80","G80","G80","G80","L80","L80","L80","L80","L80","L80","L80","D80","D80","D80","D80","D80","D80","D80","R80","R80","R80","R80","R80","R80","R80","V80","V80","V80","V80","V80","V80","V80","A81","A81","A81","A81","A81","A81","A81","C81","C81","C81","C81","C81","C81","C81","G81","G81","G81","G81","G81","G81","G81","L81","L81","L81","L81","L81","L81","L81","D81","D81","D81","D81","D81","D81","D81","R81","R81","R81","R81","R81","R81","R81","V81","V81","V81","V81","V81","V81","V81","A82","A82","A82","A82","A82","A82","A82","L82","L82","L82","L82","L82","L82","L82","G82","G82","G82","G82","G82","G82","G82","V82","V82","V82","V82","V82","V82","V82","A83","A83","A83","A83","A83","A83","A83","I83","I83","I83","I83","I83","I83","I83","G83","G83","G83","G83","G83","G83","G83","A84","A84","A84","A84","A84","A84","A84","N84","N84","N84","N84","N84","N84","N84","C84","C84","C84","C84","C84","C84","C84","I84","I84","I84","I84","I84","I84","I84","G84","G84","G84","G84","G84","G84","G84","A77","A77","A77","A77","A77","A77","A77","C77","C77","C77","C77","C77","C77","C77","V77","V77","V77","V77","V77","V77","V77","V78","V78","V78","V78","V78","V78","V78","A79","A79","A79","A79","A79","A79","A79","C79","C79","C79","C79","C79","C79","C79","G79","G79","G79","G79","G79","G79","G79","R79","R79","R79","R79","R79","R79","R79","V79","V79","V79","V79","V79","V79","V79","A80","A80","A80","A80","A80","A80","A80","C80","C80","C80","C80","C80","C80","C80","G80","G80","G80","G80","G80","G80","G80","L80","L80","L80","L80","L80","L80","L80","D80","D80","D80","D80","D80","D80","D80","R80","R80","R80","R80","R80","R80","R80","V80","V80","V80","V80","V80","V80","V80","A81","A81","A81","A81","A81","A81","A81","C81","C81","C81","C81","C81","C81","C81","G81","G81","G81","G81","G81","G81","G81","L81","L81","L81","L81","L81","L81","L81","D81","D81","D81","D81","D81","D81","D81","R81","R81","R81","R81","R81","R81","R81","V81","V81","V81","V81","V81","V81","V81","A82","A82","A82","A82","A82","A82","A82","L82","L82","L82","L82","L82","L82","L82","G82","G82","G82","G82","G82","G82","G82","V82","V82","V82","V82","V82","V82","V82","A83","A83","A83","A83","A83","A83","A83","I83","I83","I83","I83","I83","I83","I83","G83","G83","G83","G83","G83","G83","G83","A84","A84","A84","A84","A84","A84","A84","N84","N84","N84","N84","N84","N84","N84","C84","C84","C84","C84","C84","C84","C84","I84","I84","I84","I84","I84","I84","I84","G84","G84","G84","G84","G84","G84","G84","A77","A77","A77","A77","A77","A77","A77","C77","C77","C77","C77","C77","C77","C77","V77","V77","V77","V77","V77","V77","V77","V78","V78","V78","V78","V78","V78","V78","A79","A79","A79","A79","A79","A79","A79","C79","C79","C79","C79","C79","C79","C79","G79","G79","G79","G79","G79","G79","G79","R79","R79","R79","R79","R79","R79","R79","V79","V79","V79","V79","V79","V79","V79","A80","A80","A80","A80","A80","A80","A80","C80","C80","C80","C80","C80","C80","C80","G80","G80","G80","G80","G80","G80","G80","L80","L80","L80","L80","L80","L80","L80","D80","D80","D80","D80","D80","D80","D80","R80","R80","R80","R80","R80","R80","R80","V80","V80","V80","V80","V80","V80","V80","A81","A81","A81","A81","A81","A81","A81","C81","C81","C81","C81","C81","C81","C81","G81","G81","G81","G81","G81","G81","G81","L81","L81","L81","L81","L81","L81","L81","D81","D81","D81","D81","D81","D81","D81","R81","R81","R81","R81","R81","R81","R81","V81","V81","V81","V81","V81","V81","V81","A82","A82","A82","A82","A82","A82","A82","L82","L82","L82","L82","L82","L82","L82","G82","G82","G82","G82","G82","G82","G82","V82","V82","V82","V82","V82","V82","V82","A83","A83","A83","A83","A83","A83","A83","I83","I83","I83","I83","I83","I83","I83","G83","G83","G83","G83","G83","G83","G83","A84","A84","A84","A84","A84","A84","A84","N84","N84","N84","N84","N84","N84","N84","C84","C84","C84","C84","C84","C84","C84","I84","I84","I84","I84","I84","I84","I84","G84","G84","G84","G84","G84","G84","G84","A77","A77","A77","A77","A77","A77","A77","C77","C77","C77","C77","C77","C77","C77","V77","V77","V77","V77","V77","V77","V77","V78","V78","V78","V78","V78","V78","V78","A79","A79","A79","A79","A79","A79","A79","C79","C79","C79","C79","C79","C79","C79","G79","G79","G79","G79","G79","G79","G79","R79","R79","R79","R79","R79","R79","R79","V79","V79","V79","V79","V79","V79","V79","A80","A80","A80","A80","A80","A80","A80","C80","C80","C80","C80","C80","C80","C80","G80","G80","G80","G80","G80","G80","G80","L80","L80","L80","L80","L80","L80","L80","D80","D80","D80","D80","D80","D80","D80","R80","R80","R80","R80","R80","R80","R80","V80","V80","V80","V80","V80","V80","V80","A81","A81","A81","A81","A81","A81","A81","C81","C81","C81","C81","C81","C81","C81","G81","G81","G81","G81","G81","G81","G81","L81","L81","L81","L81","L81","L81","L81","D81","D81","D81","D81","D81","D81","D81","R81","R81","R81","R81","R81","R81","R81","V81","V81","V81","V81","V81","V81","V81","A82","A82","A82","A82","A82","A82","A82","L82","L82","L82","L82","L82","L82","L82","G82","G82","G82","G82","G82","G82","G82","V82","V82","V82","V82","V82","V82","V82","A83","A83","A83","A83","A83","A83","A83","I83","I83","I83","I83","I83","I83","I83","G83","G83","G83","G83","G83","G83","G83","A84","A84","A84","A84","A84","A84","A84","N84","N84","N84","N84","N84","N84","N84","C84","C84","C84","C84","C84","C84","C84","I84","I84","I84","I84","I84","I84","I84","G84","G84","G84","G84","G84","G84","G84")),
Location=as.factor(c("Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Canton","Canton","Canton","Canton","Canton","Canton","Canton","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Canton","Canton","Canton","Canton","Canton","Canton","Canton","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Canton","Canton","Canton","Canton","Canton","Canton","Canton","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Geneseo","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Riverhead","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Romulus","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Lockport","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Valatie","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Aurora","Canton","Canton","Canton","Canton","Canton","Canton","Canton","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Chazy","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Ithaca","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss","Mt. Morriss")),
Year=as.factor(c(1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1978,1978,1978,1978,1978,1978,1978,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1978,1978,1978,1978,1978,1978,1978,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1978,1978,1978,1978,1978,1978,1978,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1977,1978,1978,1978,1978,1978,1978,1978,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1979,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1981,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1983,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984,1984)),
Rep=as.factor(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4)),
Yield=c(2729,2662,2638,2680,2598,2908,2732,2753,2628,2154,2146,782,1825,1288,1157,1263,2081,2599,2699,1948,2480,1461,1265,1087,2320,1937,2230,1354,3502,2714,2547,3237,3618,3386,2648,2874,2578,1677,2020,2199,1734,1326,3352,2488,2351,3428,2849,2622,2499,2289,722,1841,2955,2103,1009,1894,983,824,1286,1299,2196,2159,1529,2884,2547,2856,2640,2977,3242,2290,2464,3231,2090,2568,2159,2166,1069,3867,3258,3144,3478,4217,4083,4035,4020,3985,2688,3974,3595,2673,3628,1728,1806,1429,2759,2259,2627,2199,2566,2100,1879,3095,2568,2430,1920,1833,1810,1498,2376,1685,1898,1830,3059,2613,2627,3042,2877,4868,2861,3023,2937,1937,2664,1754,2021,1972,3553,2619,2955,3728,3089,3753,3188,2755,2922,2697,3167,2449,3209,2728,1950,1646,2809,3553,1463,2479,1637,1525,1484,2597,2404,2798,2170,2903,3103,1825,2308,2685,2498,2664,2457,2127,1545,2007,3038,2396,2689,1946,2591,1682,2401,2863,3342,3088,2825,3160,3102,2489,3584,4488,3671,3452,2146,2077,1295,1484,1204,1520,1061,3405,1927,2212,2423,2272,2139,1930,1716,1084,1431,1713,2073,1826,1730,4511,4115,3026,5085,3767,3659,4064,3316,2307,3177,3958,3078,2923,3492,2903,2567,2964,3285,3325,3046,2875,3225,2815,2399,2791,2332,3170,2818,2206,1435,2125,2278,2033,2308,1713,4213,3360,3049,3641,4274,3376,3846,2747,2238,2425,2072,3036,3430,2951,2948,2747,1719,1839,1301,2115,1471,1024,891,2200,2254,2074,2958,2972,1965,1476,1496,1927,1497,2363,1691,2687,2861,2353,3268,3061,2422,3034,2807,2471,1725,1648,1636,880,1272,2765,2504,2286,2976,2391,3460,2416,2000,1055,2104,2625,2024,1991,2126,1445,491,1258,1484,2239,2041,1767,2660,2685,2706,3202,2357,2469,2634,2332,3205,2472,2615,2123,2384,1295,4641,3592,3589,4261,3517,4141,3382,3395,3653,3299,3488,3886,3648,2804,2072,1701,1488,2615,1766,3013,1117,1841,1810,2547,2874,2077,1981,2446,2014,1699,2040,1884,1709,2264,1484,3317,2744,2652,2755,3218,3085,2921,2956,3001,2051,2341,1780,2829,1804,3387,3007,3351,3546,3642,3844,2991,2852,2862,2600,3132,2639,2389,2524,2870,1997,2148,3321,1954,2966,3400,2348,1426,2686,3028,2500,3125,2944,2871,3595,2525,2455,2141,2549,2603,2380,2051,1877,2190,2644,2276,1958,2732,2237,2663,2728,3145,3204,2646,3589,3354,2894,3836,3017,3786,3496,2997,2092,NA,1650,1126,1443,1151,1789,2880,1867,1945,2049,2216,1996,918,1050,1439,1605,2028,2019,1581,4327,4106,3755,4253,3126,4843,3495,3148,2762,3063,3855,3514,3490,4060,3136,2593,2193,3461,3337,3391,2688,3508,2376,2654,3305,2422,2821,2882,2041,1845,1922,2224,2258,2241,1667,3818,3298,3915,4166,3977,4416,3338,2593,2454,2191,2994,3097,3265,2432,3218,2747,1307,2203,1115,1864,912,2466,1123,2440,2473,3337,2719,2327,1490,1263,1389,1459,2162,1565,1295,3046,2289,2590,2790,3367,2823,2654,2658,2619,1787,1999,1296,1467,1167,2369,2440,2382,2906,NA,NA,NA,1674,1839,1576,2203,2165,2155,2223,1013,381,1390,1646,1932,1463,2079,3020,3130,2449,3485,2366,3523,2023,2991,3305,2282,2945,2231,2230,1935,3041,2958,3565,4389,3702,4788,3147,NA,NA,NA,NA,NA,NA,NA,1866,1483,1747,1829,1798,2816,1385,2193,1698,2180,2942,2736,2565,2189,3078,2128,1807,1658,1188,2595,1740,3214,2664,2731,2701,2421,3017,3257,3098,3094,1966,2414,1379,1409,1618,3694,3520,3265,4165,2839,4289,3783,2965,2409,2673,2977,2520,2710,3144,2642,2016,2395,3358,2919,2212,1983,1968,1091,2198,2742,2520,2825,2428,3206,3272,2265,2404,2230,2346,2286,1938,2112,1888,2122,2281,2726,2446,NA,NA,NA,NA,NA,NA,NA,3966,3566,2786,3632,3897,4309,3195,2130,1895,815,1463,1222,1245,2091,1717,1416,2194,2583,2386,1831,2079,885,954,1650,1952,2192,2229,2184,4394,3950,3009,4729,3810,4237,3521,3274,3037,3255,3947,3666,3565,2957,2928,2618,2534,3025,3573,2944,2646,3016,2736,2363,3148,2612,2429,2746,2106,2067,2156,2237,2291,2130,2102,NA,NA,3031,4071,4290,4272,3598,2832,2528,2079,3218,2641,2823,2866,2732,2839,1757,2483,1114,1453,1137,NA,NA,NA,NA,NA,NA,NA,1613,1377,1341,1663,2520,2335,1924,3274,NA,2473,3516,3683,NA,2817,2759,2571,NA,2109,2266,1856,1280,3469,2038,NA,3310,NA,NA,NA,1404,813,1749,2198,2131,1917,1995,1004,616,1178,1568,1486,981,1472,3098,2771,2309,3495,3104,3164,1930,NA,NA,NA,NA,NA,NA,NA,4061,2960,3204,4241,4112,3993,3501,NA,NA,NA,NA,NA,NA,NA,2073,1326,1671,2279,2170,1990,2848,NA,NA,NA,NA,NA,NA,NA,2419,2442,1871,1944,1821,1898,2076,2545,2404,2535,3555,2798,3487,2785,3144,3170,1431,2677,1707,2470,1441,2661,2415,3273,3915,3961,4221,2966,3310,2654,2585,2742,2671,2957,2716,2642,2333,2968,2845,NA,2467,2255,2309,1545,1920,3028,2650,3750,2757,2912,3807,2452,1921,2580,2279,1697,2285,1770,1765,2413,NA,2556,2605,NA,NA,NA,NA,NA,NA,NA,3897,3159,2738,3797,4204,3905,3134,1812,1579,1251,2447,1190,1384,1083,3432,2272,1808,2305,2074,2045,1866,1602,1032,2222,1536,2130,1789,1925,4778,3881,3529,4402,3564,3506,3409,2898,2764,3255,3682,3239,3719,3681,3010,2627,2828,3107,3241,3422,2601,2983,2834,2375,2989,2930,2721,2244,1450,1449,2112,2297,1997,2305,2179,NA,NA,NA,NA,4557,4006,3996)
)
```

```{r}
summary(aov(Yield ~ Entry*Environment,data=ny84.dat))
ny.res <- standard.sensitivity.plot(ny84.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=FALSE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(ny.res)

ny.res <- standard.sensitivity.plot(ny84.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(ny.res)

ny84sub.dat <- subset(ny84.dat,ny84.dat$Entry!="CHIP")
nysub.res <- standard.sensitivity.plot(ny84sub.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1977,1978,1979)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1978,1979,1980)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1979,1980)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1979,1980,1981)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1981,1982)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1982,1983)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)

ny84sub2.dat <- subset(ny84.dat,(ny84.dat$Year %in% c(1983,1984)))
nysub2.res <- standard.sensitivity.plot(ny84sub2.dat,
                                     response = "Yield",
                          TreatmentName = "Entry",
                          TrialName = "Environment",
                          RepName="Rep",
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)
print.stdplot(nysub2.res)
means.hc <- ny.res$cluster$means.hc
ref.hc <- ny.res$add.cluster$means.hc

matched.idx <- compare.merges(means.hc$merge,ref.hc$merge)

  
  #determine clusters
  x.clfl<-means.hc$height
  #assign the fusion levels
  x.clm<-mean(x.clfl)
  #compute the means
  x.cls<-sqrt(var(x.clfl))
  #compute the standard deviation
  x.score <- ((x.clfl-x.clm)/x.cls)
  #Mojena(1977)2.75<k<3.5
  #Milligan and Cooper (1985) k=1.25
  extra <- x.score[x.score<1.25]
  clusters <- cutree(means.hc,h=x.clfl[length(extra)-1])
  
  current.clfl<-means.hc$height[2]
        #compute the standard deviation
        x.score <-(current.clfl/x.cls) 
        
```

```{r}
response = "Plot.Mean"
TreatmentName = "Criteria.Entry.No."
TrialName = "Expt.No."
RepName="Rep.No."
#yield.desc ="Yield"
#tw.desc="Test Weight"
#hd.desc="Heading"
#ht.desc="Test Weight"
#cpt.dat <- read.csv("CPT.full.subset.csv",header=TRUE)
#cpt.dat <- read.csv("CPT_2007Subsetb.csv",header=TRUE)


yield.desc ="GY"
tw.desc ="TW"
hd.desc="HD"
ht.desc="HT"
cpt.dat <- read.delim("CPT_2007Subset.txt",header=TRUE)
cpt.dat <- subset(cpt.dat,!is.na(cpt.dat$Plot.Mean))
cpt.dat$Expt.No. <- as.factor(cpt.dat$Expt.No.)
TrtNames <- as.character(cpt.dat$Criteria.Entry.No.)
TrtNames[cpt.dat$Criteria.Entry.No.<10] <- paste("0",TrtNames[cpt.dat$Criteria.Entry.No.<10],sep="")
cpt.dat$Criteria.Entry.No. <- as.factor(TrtNames)
cpt.dat$Rep.No. <- as.factor(cpt.dat$Rep.No.)
gy.dat <- subset(cpt.dat,cpt.dat$Description==yield.desc)
tw.dat <- subset(cpt.dat,cpt.dat$Description==tw.desc)
hd.dat <- subset(cpt.dat,cpt.dat$Description==hd.desc)
ht.dat <- subset(cpt.dat,cpt.dat$Description==ht.desc)

gy.dat$Expt.No. <- as.factor(as.character(gy.dat$Expt.No.))
tw.dat$Expt.No. <- as.factor(as.character(tw.dat$Expt.No.))
hd.dat$Expt.No. <- as.factor(as.character(hd.dat$Expt.No.))
ht.dat$Expt.No. <- as.factor(as.character(ht.dat$Expt.No.))
```

```{r}
gy.means <- gei.table.and.effects(gy.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName)
gy.means$trial.means
colMeans(gy.means$means.table)
gy.res <- standard.sensitivity.plot(gy.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          dual.dendrogram=FALSE,
                          plot.outliers=TRUE,legend.columns=3)
gy.res <- standard.sensitivity.plot(gy.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          outliers=2.4,
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)

print.stdplot(gy.res)

gyb.res <- standard.sensitivity.plot(gy.dat,
                          response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          outliers=2,
                          method="ave",
                          plot.outliers=TRUE,legend.columns=3)

gy2.res <- standard.sensitivity.plot(gy.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          outliers=2.4,
                          dual.dendrogram=TRUE,
                          method="ave",
                          plot.outliers=TRUE,legend.columns=3)

means.matrix <- tapply(gy.dat$Plot.Mean,list(gy.dat$Criteria.Entry.No.,gy.dat$Expt.No.),mean)
decomp <- decompose.means.table(means.matrix)
txt.matrix <- decomp$gamma
mean(unlist(txt.matrix),na.rm=TRUE)
max <- sd(unlist(txt.matrix),na.rm=TRUE)
norm.mat <- abs(txt.matrix)
crit <- 3*max
gy.means$means.table - means.matrix

gy.res$cluster$score/gy.res$add.cluster$score
gy.res$cluster$clusters
gy.res$add.cluster$clusters
gy.res$cluster$means.hc$height
gy.res$add.cluster$means.hc$height

gy.res$cluster$means.hc$height/gy.res$add.cluster$means.hc$height
gy.res$cluster$means.hc$order
gy.res$add.cluster$means.hc$order

gy.res$cluster$means.hc$merge
gy.res$add.cluster$means.hc$merge

gy.res$cluster$means.hc$merge==gy.res$add.cluster$means.hc$merge

```

```{r}
tw.res <- standard.sensitivity.plot(tw.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          dual.dendrogram=TRUE,
                          plot.outliers=TRUE,legend.columns=3)

print.stdplot(tw.res)
tw.res$cluster$score/tw.res$add.cluster$score
tw.res <- standard.sensitivity.plot(tw.dat,
                                     response = response,
                          TreatmentName = TreatmentName,
                          TrialName = TrialName,
                          RepName=RepName,
                          dual.dendrogram=FALSE,
                          plot.outliers=TRUE,legend.columns=3)


```


```{r}
gy.matrix <- data.frame(tapply(gy.dat$Plot.Mean,list(gy.dat$Expt.No.,gy.dat$Criteria.Entry.No.),mean))
gy.vector <- tapply(gy.dat$Plot.Mean,list(gy.dat$Expt.No.),mean)

par(fig = c(0, 1, 0.4, 1), mar = (c(1, 4, 1, 1) + 0.1))
gy.table <- plot.interaction.ARMST(gy.matrix, gy.vector, ylab='Treatment in Trial Mean',
                      regression=TRUE, main='GY', show.legend=TRUE,legend.pos=c(.01,.98),
                      legend.columns=4,lwd = 1
                      )
par(fig=c(0,1,0,.4),mar=(c(5, 4, 0, 1) + 0.1), new=TRUE)
gy.hc <- plot.clusters.ARMST(gy.matrix, gy.vector, xlab='Trial Mean', ylab='')
par(fig = c(0, 1, 0, 1))

tw.matrix <- data.frame(tapply(tw.dat$Plot.Mean,list(tw.dat$Expt.No.,tw.dat$Criteria.Entry.No.),mean))
tw.vector <- tapply(tw.dat$Plot.Mean,list(tw.dat$Expt.No.),mean)
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 4, 1, 1) + 0.1))
tw.table <- plot.interaction.ARMST(tw.matrix, tw.vector, ylab='Treatment in Trial Mean',
                      regression=TRUE, main='TW', show.legend=TRUE,legend.pos=c(.01,.98),
                      legend.columns=4,lwd = 1
                      )
par(fig=c(0,1,0,.4),mar=(c(5, 4, 0, 1) + 0.1), new=TRUE)
tw.hc <- plot.clusters.ARMST(tw.matrix, tw.vector, xlab='Trial Mean', ylab='')
par(fig = c(0, 1, 0, 1))

hd.matrix <- data.frame(tapply(hd.dat$Plot.Mean,list(hd.dat$Expt.No.,hd.dat$Criteria.Entry.No.),mean))
hd.vector <- tapply(hd.dat$Plot.Mean,list(hd.dat$Expt.No.),mean)
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 4, 1, 1) + 0.1))
hd.table <- plot.interaction.ARMST(hd.matrix, hd.vector, ylab='Treatment in Trial Mean',
                      regression=TRUE, main='HD', show.legend=TRUE,legend.pos=c(.01,.98),
                      legend.columns=4,lwd = 1
                      )
par(fig=c(0,1,0,.4),mar=(c(5, 4, 0, 1) + 0.1), new=TRUE)
hd.hc <- plot.clusters.ARMST(hd.matrix, hd.vector, xlab='Trial Mean', ylab='')
par(fig = c(0, 1, 0, 1))


ht.matrix <- data.frame(tapply(ht.dat$Plot.Mean,list(ht.dat$Expt.No.,ht.dat$Criteria.Entry.No.),mean))
ht.vector <- tapply(ht.dat$Plot.Mean,list(ht.dat$Expt.No.),mean)
par(fig = c(0, 1, 0.4, 1), mar = (c(1, 4, 1, 1) + 0.1))
ht.table <- plot.interaction.ARMST(ht.matrix, ht.vector, ylab='Treatment in Trial Mean',
                      regression=TRUE, main='HT', show.legend=TRUE,legend.pos=c(.01,.98),
                      legend.columns=4,lwd = 1
                      )
par(fig=c(0,1,0,.4),mar=(c(5, 4, 0, 1) + 0.1), new=TRUE)
ht.hc <- plot.clusters.ARMST(ht.matrix, ht.vector, xlab='Trial Mean', ylab='')
par(fig = c(0, 1, 0, 1))
```