---
title: "Nearest Neighbor"
author: "Peter Claussen"
date: "May 23, 2016"
output: html_document
---

Documenting methods for nearest neighbor analysis.

We'll start with the discussion in Plant, 16.3, p 522

Dependencies
```{r}
library(mgcv)
library(deldir)
library(spdep) #cell2nb
```

```{r}
# This is from 16.2
library(spatstat)
library(maptools)
data.Yield4.1 <- read.csv("./created/set4.1yld96cleaned.csv", header = TRUE)
coordinates(data.Yield4.1) <- c("Easting","Northing")
E <- 592400
W <- 592050
S <- 4270400
N <- 4271100
cell.size <- 350 / 6
xmin <- W + cell.size / 2
xmax <- E - cell.size / 2
ymin <- S + cell.size / 2
ymax <- N - cell.size / 2
cell.ctrs <- expand.grid(seq(xmax, xmin, -cell.size),
      seq(ymin, ymax, cell.size))
cell.ppp <- ppp(cell.ctrs[,1], cell.ctrs[,2],
     window = owin(c(W, E), c(S, N)))
plots.pp <- dirichlet(cell.ppp)
plots.sp <- as(plots.pp, "SpatialPolygons")
row.names(plots.sp) = as.character(1:72)
plots.spdf <- SpatialPolygonsDataFrame(plots.sp,
  data = data.frame(ID = as.character(72:1),
  row.names = as.character(1:72)))
```


```{r}
#RCB.lm <- lm(Yield ~ trtmt.RCB + block,
#  data = plots.spdf@data)
library(agridat)
data(connolly.potato)
desplot(yield~col*row, data=connolly.potato, out1=rep, main="connolly.potato yields")

RCB.lm <- lm(yield ~ gen + rep,
  data = connolly.potato)
print(RCB.sum <- summary(RCB.lm))

tau.dif1 <- coef(RCB.sum)[2:18,1]

tau.hat <- c(0, tau.dif1)

library(vegan)
print(vegdist(tau.hat[1:4], method = "euclidean"), digits = 3)
tau.dist <- vegdist(tau.hat, method = "euclidean")

# Computation of EMP

print(EMP.RCB <- 2 * sum(tau.dist^2) / (18*17))

# Monte Carlo simuation
EMP.calc <- function(trt.data, form.lm){
   trt.data$gen <- factor(unlist(tapply(rep(1:20,4),
      sort(rep(1:4,20)), sample)))
   trt.sum <- summary(lm(form.lm, data = trt.data))
   tau.dif1 <- coef(trt.sum)[2:20,1]
   tau.hat <-  c(0, tau.dif1)
   tau.dist <- vegdist(tau.hat, method = "euclidean")
   EMP <- 2 * sum(tau.dist^2) / (20*19)
   return(EMP)
}


set.seed(123)
RCB.form <- as.formula(yield ~ gen + rep)
U <- replicate(100, EMP.calc(connolly.potato, RCB.form))
print(EMP.RCB <- mean(U))

```

```{r}
# Papadakis method
trt.means <- tapply(connolly.potato$yield,
  connolly.potato$gen, mean)
yield.e <- connolly.potato$yield -
    sapply(connolly.potato$gen, function(x) trt.means[x])

connolly.potato$yield.e <- yield.e

nb20x4 <- cell2nb(20,4)
W.papa <- nb2listw(nb20x4)
connolly.potato$X <- listw2mat(W.papa) %*% yield.e

set.seed(123)
papa.form <- as.formula(yield ~ gen + X)
U <- replicate(100, EMP.calc(connolly.potato, papa.form))
print(EMP.papa <- mean(U))
print(EMPbar.papa <- 100 * EMP.papa / EMP.RCB)
```

```{r}
add.plot.centers <- function(plan,plot.dim=c(1,1),row.buffer=0) {
  plan$x <- 0
  plan$y <- 0
  
  half.width <- plot.dim[1]/2
  half.heigth <- plot.dim[2]/2
  for(idx in 1:dim(plan)[1]) {
    row <- plan$row[idx]
    col <- plan$col[idx]
    plan$x[idx] <- half.width + (col-1)*plot.dim[1] + (col-1)*row.buffer
    plan$y[idx] <- half.heigth + (row-1)*plot.dim[2] + (row-1)*row.buffer
  }
  return(plan)
}
```

Trend Analysis

```{r}
connolly.potato <- add.plot.centers(connolly.potato)
yield.trend <- lm(yield ~ x + y + I(x^2) +  I(y^2) + I(x*y), data =connolly.potato)
connolly.potato$trend <- predict(yield.trend)
```

```{r}
library(nlme)

model.gls <- gls(yield ~ gen + trend, data = connolly.potato)
# Check that the trend looks reasonable
trellis.device(color = FALSE)
plot(Variogram(model.gls, form = ~ x + y,
   maxDist = 1), xlim = c(0,1),
   main = "Variogram of Residuals")
model.gls2 <- update(model.gls,
   corr = corSpher(value = c(0.35, 0.5),
   form = ~ x + y, nugget = TRUE))
connolly.potato$gls.trend <- predict(model.gls2)
```

```{r}
desplot(X~col*row, data=connolly.potato, out1=rep, main="connolly.potato deviations")
desplot(trend~col*row, data=connolly.potato, out1=rep, main="connolly.potato trend")
desplot(gls.trend~col*row, data=connolly.potato, out1=rep, main="connolly.potato gls.trend")
```

```{r}
rcb.lm <- lm(yield ~ gen + rep,data=connolly.potato)
papa.lm <- lm(yield ~ gen + X,data=connolly.potato)
trend.lm <- lm(yield ~ gen + trend,data=connolly.potato)
trendgls.lm <- lm(yield ~ gen + gls.trend,data=connolly.potato)
summary(rcb.lm)
anova(rcb.lm)
summary(papa.lm)
anova(papa.lm)
summary(trend.lm)
anova(trend.lm)

summary(model.gls2)
anova(model.gls2)

library(lsmeans)
lsmeans(rcb.lm,cld~gen)
lsmeans(papa.lm,cld~gen)
lsmeans(trend.lm,cld~gen)
lsmeans(trendgls.lm,cld~gen)
#lsmeans(model.gls2,cld~gen)
connolly.potato
```