---
title: "Spatial Nature of Randomization"
author: "Peter Claussen"
date: "July 1, 2014"
output: html_document
---

```{r}
library(ggplot2)
library(grid) #textGrob
library(gridExtra) #grid.arrange
library(agridat)
source("../ASA_CSSA_SSSA/R/contrast.distances.R")
source("../ASA_CSSA_SSSA/R/average.distances.R")
source("../ASA_CSSA_SSSA/R/pair.distances.R")
source("../ASA_CSSA_SSSA/R/plot.distance.R")
source("../ASA_CSSA_SSSA/R/expected.adtc.R")
```

We start with the quality of randomization as described in "Spatial Nature of Randomization and Its Effect on the Outcome of Field Experiments", van Es and van Es (1993) Agron J. 85:420-428.

Figure 2 presents "A realization of randomized treatment allocation for a RCB design with four treatments and four replications"
```{r}
Fig2.plan <- data.frame(
     trt=c(4,1,3,2,1,3,4,2,3,2,4,1,2,3,4,1),
     row=c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)),
     col=c(rep(1:4,4))
  )
desplot(trt ~ col*row, data=Fig2.plan, num=trt, main="Figure 2")
Fig2.mat <- make.pairs.matrices(make.pairs.table(pair.distances(Fig2.plan)))
Fig2.mat
```

Scott 1993 
```{r}
Scott.plan <- data.frame(
  row=c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3),
  col=c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  trt=c(1, 5, 7, 2, 6, 8, 3, 10, 4, 9, 11, 12, 3, 14, 13, 1, 16, 2, 15, 4, 1, 19, 1, 2, 21, 18, 3, 20, 4, 17)
)
desplot(trt ~ col*row, data=Scott.plan, num=trt, main="Scott 1993")
Scott.mat <- make.pairs.matrices(make.pairs.table(pair.distances(Scott.plan,reference=1:4)))
Scott.mat

make.pairs.matrices(make.pairs.table(pair.distances(Scott.plan,multiple=FALSE)))
make.pairs.matrices(make.pairs.table(pair.distances(Scott.plan,reference=1:4,multiple=FALSE)))
make.pairs.matrices(make.pairs.table(pair.distances(Scott.plan)))
```



```{r}
source('../ASA_CSSA_SSSA/R/augment.plan.R')
source('../ASA_CSSA_SSSA/R/make.plan.R')
source('../ASA_CSSA_SSSA/R/weave.R')
source('../ASA_CSSA_SSSA/R/cycle.R')

plan <- data.frame(
     trt=c(4,1,3,2,1,3,4,2,3,2,4,1,2,3,4,1),
     row=c(rep(1,4),rep(2,4),rep(3,4),rep(4,4)),
     col=c(rep(1:4,4))
  )

v_t <- max(plan$trt)
v_r <- 4

v_1 <- 1:80
v_1 <- v_1 + v_t

plan0<-make.plan(augment.plan(plan,v_1,0))
plan1<-make.plan(augment.plan(plan,v_1,1))
plan2<-make.plan(augment.plan(plan,v_1,2))
plan3<-make.plan(augment.plan(plan,v_1,3))
plan4<-make.plan(augment.plan(plan,v_1,4))
plan5<-make.plan(augment.plan(plan,v_1,5))
plan6<-make.plan(augment.plan(plan,v_1,6))

plan0$check <- plan0$trt %in% 1:v_t
plan1$check <- plan1$trt %in% 1:v_t
plan2$check <- plan2$trt %in% 1:v_t
plan3$check <- plan3$trt %in% 1:v_t
plan4$check <- plan4$trt %in% 1:v_t
plan5$check <- plan5$trt %in% 1:v_t
plan6$check <- plan6$trt %in% 1:v_t

desplot(trt ~ col*row, data=plan0, num=trt, main="0 stagger")
desplot(trt ~ col*row, data=plan3, num=trt, main="3 stagger")

desplot(check ~ col*row, data=plan0, main="0 stagger")
desplot(check ~ col*row, data=plan1, main="1 stagger")
desplot(check ~ col*row, data=plan2, main="2 stagger")
desplot(check ~ col*row, data=plan3, main="3 stagger")
desplot(check ~ col*row, data=plan4, main="4 stagger")
desplot(check ~ col*row, data=plan5, main="5 stagger")
desplot(check ~ col*row, data=plan6, main="6 stagger")
```

```{r}
subset(plan0,plan0$trt==5)
subset(plan0,plan0$trt==1)
#plan0
#pair.distances(plan0,reference=1:v_t)
plan0.mat <- make.pairs.matrices(make.pairs.table(pair.distances(plan0,reference=1:v_t)))
#plan0.mat

plan2.mat <- make.pairs.matrices(make.pairs.table(pair.distances(plan2,reference=1:v_t)))

plan3.mat <- make.pairs.matrices(make.pairs.table(pair.distances(plan3,reference=1:v_t)))
#plan3.mat

apply(plan0.mat$min,1,min,na.rm=TRUE)
apply(plan2.mat$min,1,min,na.rm=TRUE)
apply(plan3.mat$min,1,min,na.rm=TRUE)

apply(plan0.mat$mean,1,mean,na.rm=TRUE)
apply(plan3.mat$mean,1,mean,na.rm=TRUE)

min0.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan0,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min1.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan1,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min2.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan2,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min3.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan3,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min4.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan4,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min5.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan5,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min6.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan6,reference=1:v_t)))$min,1,min,na.rm=TRUE)

min0.means
min1.means
min2.means
min3.means
min4.means
min5.means
min6.means

mean(min0.means[v_1])
mean(min1.means[v_1])
mean(min2.means[v_1])
mean(min3.means[v_1])
mean(min4.means[v_1])
mean(min5.means[v_1])
mean(min6.means[v_1])
```

```{r}
if(!file.exists("staggers.dat.Rda")) {
  min.mean <- c()
 staggers <- c()
 replicate <- c()
 unreplicated <- c()
 ratio <- c()
 avg.mean <- c()
 ratios <- c(2,4,8,12,16,24,32)
 for(rat in ratios) {
   max.v1 = rat*v_t*v_r
   v_1 <- 1:max.v1
   
   v_1 <- v_1 + v_t
   
   stagger <- 1:rat

   for(idx in 1:30) {
     for (st in stagger) {
      plan0<-make.plan(augment.plan(plan,v_1,st))
          plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t)))
      min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
      avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
      avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    
      min.mean <- c(min.mean,mean(min0.means[v_1]))
      staggers <- c(staggers,st)
      unreplicated <- c(unreplicated,max.v1)
      ratio <- c(ratio,rat)
      replicate <- c(replicate, idx)
   }
 }
 }
 
  staggers.dat <- data.frame(
   min.mean=min.mean,
   avg.mean=avg.mean,
   staggers=staggers,
   replicate=replicate,
   ratio=ratio,
   unreplicated=unreplicated
 )
 save(staggers.dat, file="staggers.dat.Rda")
 
} else {
  load(file="staggers.dat.Rda")
}

staggers.dat$ratio <- as.factor(staggers.dat$ratio)

staggers.dat$avg.scaled <- staggers.dat$avg.mean/(tapply(staggers.dat$avg.mean,list(staggers.dat$ratio),min)[staggers.dat$ratio])
                                                  
ggplot(staggers.dat, aes(staggers, avg.mean)) + 
  geom_point(aes(shape = ratio, color=ratio),size=2)
ggplot(staggers.dat, aes(staggers, avg.scaled)) + 
  geom_point(aes(shape = ratio, color=ratio),size=2)
```

```{r}
staggers.dat$min.scaled <- staggers.dat$min.mean/max(staggers.dat$min.mean)
staggers.dat$min.scaled <- staggers.dat$min.mean/(tapply(staggers.dat$min.mean,list(staggers.dat$ratio),min)[staggers.dat$ratio])
ggplot(staggers.dat, aes(staggers, min.mean)) + 
  geom_point(aes(color=ratio),size=2) + 
  geom_smooth(aes(group=ratio),se=FALSE) 
ggplot(staggers.dat, aes(staggers, min.scaled)) + 
  geom_point(aes(color=ratio),size=2) + 
  geom_smooth(aes(group=ratio),se=FALSE) 
```



```{r}
v_1 <- 1:80
v_1 <- v_1 + v_t

plan0<-make.plan(augment.plan(plan,v_1,0))
plan1<-make.plan(augment.plan(plan,v_1,1))
plan2<-make.plan(augment.plan(plan,v_1,2))
plan3<-make.plan(augment.plan(plan,v_1,3))
plan4<-make.plan(augment.plan(plan,v_1,4))

plan0$check <- plan0$trt %in% 1:v_t
plan1$check <- plan1$trt %in% 1:v_t
plan2$check <- plan2$trt %in% 1:v_t
plan3$check <- plan3$trt %in% 1:v_t
plan4$check <- plan4$trt %in% 1:v_t

desplot(check ~ col*row, data=plan0, main="0 stagger")
desplot(check ~ col*row, data=plan1, main="1 stagger")
desplot(check ~ col*row, data=plan2, main="2 stagger")
desplot(check ~ col*row, data=plan3, main="3 stagger")
desplot(check ~ col*row, data=plan4, main="4 stagger")
```

```{r}
min0.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan0,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min1.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan1,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min2.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan2,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min3.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan3,reference=1:v_t)))$min,1,min,na.rm=TRUE)
min4.means <- apply(make.pairs.matrices(make.pairs.table(pair.distances(plan4,reference=1:v_t)))$min,1,min,na.rm=TRUE)

min0.means
min1.means
min2.means
min3.means
min4.means

mean(min0.means[v_1])
mean(min1.means[v_1])
mean(min2.means[v_1])
mean(min3.means[v_1])
mean(min4.means[v_1])
```




```{r}
v_1 <- 1:240
v_1 <- v_1 + v_t

plan4<-make.plan(augment.plan(plan,v_1,4))

plan4$check <- plan4$trt %in% 1:v_t
desplot(check ~ col*row, data=plan4, main="4 stagger")

plan8<-make.plan(augment.plan(plan,v_1,8))

plan8$check <- plan8$trt %in% 1:v_t
desplot(check ~ col*row, data=plan8, main="8 stagger")

```


### Variations on plot size and stagger, 240 unreplicated

```{r}
if(!file.exists("staggers.240.dat.Rda")) {
min.mean <- c()
avg.mean <- c()
staggers <- c()
replicate <- c()
row.width <- c()
col.width <- c()

stagger <- 0:16
v_1 <- 1:240
v_1 <- v_1 + v_t

for(idx in 1:30) {
  replicate <- c(replicate, idx)
  
  for (st in stagger) {
    plan0<-make.plan(augment.plan(plan,v_1,st))
    plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t)))
    min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
    min.mean <- c(min.mean,mean(min0.means[v_1]))
    avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
    avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    staggers <- c(staggers,st)
    row.width <- c(row.width,1)
    col.width <- c(col.width,1)
    
    plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t,plot.dim=c(1,2),buffer.dim=c(0,0))))
    min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
    min.mean <- c(min.mean,mean(min0.means[v_1]))
    avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
    avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    staggers <- c(staggers,st)
    row.width <- c(row.width,1)
    col.width <- c(col.width,2)
    
    
    plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t,plot.dim=c(1,4),buffer.dim=c(0,0))))
    min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
    min.mean <- c(min.mean,mean(min0.means[v_1]))
    avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
    avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    staggers <- c(staggers,st)
    row.width <- c(row.width,1)
    col.width <- c(col.width,4)
    
    
    plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t,plot.dim=c(2,1),buffer.dim=c(0,0))))
    min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
    min.mean <- c(min.mean,mean(min0.means[v_1]))
    avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
    avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    staggers <- c(staggers,st)
    row.width <- c(row.width,2)
    col.width <- c(col.width,1)
    
    plan.mat <- make.pairs.matrices(
                      make.pairs.table(
                        pair.distances(plan0,reference=1:v_t,plot.dim=c(4,1),buffer.dim=c(0,0))))
    min0.means <- apply(plan.mat$min,1,min,na.rm=TRUE)
    min.mean <- c(min.mean,mean(min0.means[v_1]))
    avg0.mean <- apply(plan.mat$mean,1,mean,na.rm=TRUE)
    avg.mean <- c(avg.mean,mean(avg0.mean[v_1]))
    staggers <- c(staggers,st)
    row.width <- c(row.width,4)
    col.width <- c(col.width,1)
  }
}


 staggers.240.dat <- data.frame(
   min.mean=min.mean,
   avg.mean=avg.mean,
   staggers=staggers,
   replicate=replicate,
   row.width=row.width,
   col.width=col.width
 )

 save(staggers.240.dat, file="staggers.240.dat.Rda")
 
} else {
  load(file="staggers.240.dat.Rda")
}
```

```{r}
staggers.240.dat$plot.dim <- as.factor(staggers.240.dat$row.width):as.factor(staggers.240.dat$col.width)
```

```{r}

staggers.240.dat$avg.scaled <- staggers.240.dat$avg.mean/(tapply(staggers.240.dat$avg.mean,list(staggers.240.dat$plot.dim),min)[staggers.240.dat$plot.dim])

ggplot(staggers.240.dat, aes(staggers, avg.mean)) + 
  geom_point(aes(shape = plot.dim, color=plot.dim),size=2)
ggplot(staggers.240.dat, aes(staggers, avg.scaled)) + 
  geom_point(aes(shape = plot.dim, color=plot.dim),size=2)
```

```{r}

staggers.240.dat$min.scaled <- staggers.240.dat$min.mean/(tapply(staggers.240.dat$min.mean,list(staggers.240.dat$plot.dim),min)[staggers.240.dat$plot.dim])


ggplot(staggers.240.dat, aes(staggers, min.mean)) + 
  geom_point(aes(shape = plot.dim, color=plot.dim),size=2) + 
  geom_smooth(aes(group= plot.dim),se=FALSE) 
ggplot(staggers.240.dat, aes(staggers, min.scaled)) + 
  geom_point(aes(shape = plot.dim, color=plot.dim),size=2) + 
  geom_smooth(aes(group= plot.dim),se=FALSE) 
```

